spring.application.name=search-service
server.port=8083

# ─── CIRCUIT BREAKER ───────────────────────────────────────────
resilience4j.circuitbreaker.instances.file-service.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.file-service.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.file-service.wait-duration-in-open-state=10000
resilience4j.circuitbreaker.instances.file-service.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.file-service.automatic-transition-from-open-to-half-open-enabled=true

spring.cloud.openfeign.circuitbreaker.enabled=true
